# This runs `miri`

name: Miri

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  miri:
    runs-on: ubuntu-latest
    steps:
    - name: Cache
      uses: actions/cache@v3.2.3
      with:
        path: |
          ~/.cargo
          target
        key: miri
    - uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Miri
      run: |
        rustup toolchain install nightly --component miri
        rustup override set nightly
        cargo miri setup
        cargo miri test --release -- --skip float::tests::special --skip int::tests::special --skip percent::tests::special --skip runtime::tests::special --skip unsigned::tests::special
